# Generated by Django 4.2.11 on 2024-04-21 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_post_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('group_type', models.CharField(blank=True, choices=[('floor', 'Floor'), ('building', 'Building'), ('multi-storey-apartment', 'Multi Storey Apartment')], max_length=255)),
                ('address_segment', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(null=True, upload_to='property_images/')),
                ('re_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.property')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_details', models.FileField(null=True, upload_to='transaction_documents/')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_transactions', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.property')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RentalLease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('stop_date', models.DateField()),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_frequency', models.CharField(max_length=255)),
                ('rent_agreement_document', models.FileField(null=True, upload_to='rental_agreements/')),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_leases', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.property')),
                ('tenant_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_leases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=255, unique=True)),
                ('housing_type', models.CharField(choices=[('apartment', 'Apartment'), ('studio', 'Studio'), ('flat', 'Flat'), ('plot', 'Plot')], max_length=255)),
                ('area_sq_ft', models.IntegerField()),
                ('image', models.ImageField(null=True, upload_to='property_unit_images/')),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('property', 'start_date')},
            },
        ),
    ]
